In [2]:
import numpy as np

Question #1

In [2]:
def prob1():
    A = np.array([[3, -1, 4],
                  [1, 5, -9]])
    B = np.array([[2, 6, -5, 3],
                  [5, -8, 9, 7],
                  [9, -3, -2, -3]])
    prod = np.dot(A,B)
    return prod

print(prob1())

[[ 37  14 -32 -10]
 [-54  -7  58  65]]


Question #2

In [36]:
def prob2():
    A = np.array([[3, 1, 4],
                  [1, 5, 9],
                  [-5, 3, 1]])
    P = np.dot(A,A)
    Q = np.dot(A,P)
    return -Q + 9*P - 15*A

print(prob2())

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Question #3

In [3]:
def prob3():
    A = np.ones((7, 7), dtype = np.int)
    B = A
    A = np.triu(A)
    B = -1*B
    B = np.tril(B)
    # I had a difficult time getting fill_diagonal() due to using Python 2
    for i in range(0,7):
        for j in range(0,7):
            if B[i,j] == 0:
                B[i,j] = 5
    return np.dot(np.dot(A,B),A)
print(prob3())

[[ -7  -8  -3   8  25  48  77]
 [ -6 -12 -12  -6   6  24  48]
 [ -5 -10 -15 -14  -7   6  25]
 [ -4  -8 -12 -16 -14  -6   8]
 [ -3  -6  -9 -12 -15 -12  -3]
 [ -2  -4  -6  -8 -10 -12  -8]
 [ -1  -2  -3  -4  -5  -6  -7]]


Question #4

In [38]:
A = np.random.randint(-10, 10, size = (5,5))
def prob4(a):
    K = np.copy(a)
    mask = K < 0
    K[mask] = 0
    return K

print(prob4(A))

[[0 8 9 0 9]
 [6 6 5 0 3]
 [5 0 4 0 6]
 [0 0 3 0 0]
 [0 6 0 2 0]]


Question #5

In [39]:
def prob5():
    A = np.arange(6).reshape(2,3)
    AT = A.transpose()
    B = np.tril(3*np.ones((3,3)))
    C = -2*np.eye(3)
    I = np.identity(3)
    Z33 = 0*np.eye(3)
    Z22 = 0*np.eye(2)
    Z23 = np.zeros_like(A)
    Z32 = Z23.transpose()
    k1 = np.vstack((Z33, A, B))
    k2 = np.vstack((AT, Z22, Z32))
    k3 = np.vstack((I, Z23, C))
    K  = np.hstack((k1, k2, k3))
    return K

print(prob5())

[[ 0.  0.  0.  0.  3.  1.  0.  0.]
 [ 0.  0.  0.  1.  4.  0.  1.  0.]
 [ 0.  0.  0.  2.  5.  0.  0.  1.]
 [ 0.  1.  2.  0.  0.  0.  0.  0.]
 [ 3.  4.  5.  0.  0.  0.  0.  0.]
 [ 3.  0.  0.  0.  0. -2. -0. -0.]
 [ 3.  3.  0.  0.  0. -0. -2. -0.]
 [ 3.  3.  3.  0.  0. -0. -0. -2.]]


Question #6

In [40]:
K = np.arange(9, dtype = float).reshape((3,3))
def prob6(A):
    F = np.transpose(np.transpose(A) / A.sum(axis = 1))
    return F

print(prob6(K))

[[ 0.          0.33333333  0.66666667]
 [ 0.25        0.33333333  0.41666667]
 [ 0.28571429  0.33333333  0.38095238]]


Question #7

In [24]:
def prob7(K):
    vh = np.max(K[:,:-3] * K[:,1:-2] * K[:,2:-1] * K[:,3:])
    vv = np.max(K[:-3,:] * K[1:-2,:] * K[2:-1,:] * K[3:,:])
    vr = np.max(K[:-3,:-3] * K[1:-2,1:-2] * K[2:-1,2:-1] * K[3:,3:])
    vl = np.max(K[3:,:-3] * K[2:-1,1:-2] * K[1:-2,2:-1] * K[:-3,3:])
    return max(vh,vv,vr,vl)

#print(prob7(grid))